import { User, Service, Badge, Review } from "@/types";

const mockBadges: Badge[] = [
  {
    id: "1",
    name: "First Trade",
    icon: "🤝",
    description: "Completed your first trade",
    earnedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "5-Star Provider",
    icon: "⭐",
    description: "Received 5 consecutive 5-star reviews",
    earnedAt: new Date("2024-02-20"),
  },
  {
    id: "3",
    name: "Trusted Member",
    icon: "✅",
    description: "Verified identity and qualifications",
    earnedAt: new Date("2024-01-10"),
  },
  {
    id: "4",
    name: "Community Builder",
    icon: "🏆",
    description: "Completed 10+ trades",
    earnedAt: new Date("2024-03-01"),
  },
];

export const mockUsers: User[] = [
  {
    id: "1",
    email: "sean.murphy@email.ie",
    name: "Seán Murphy",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    location: "Dublin",
    bio: "Professional tiler with 15 years experience. Father of two looking for childcare help!",
    credits: 45,
    verificationStatus: "verified",
    badges: [mockBadges[0], mockBadges[2], mockBadges[3]],
    joinedAt: new Date("2024-01-01"),
    completedTrades: 12,
    rating: 4.9,
  },
  {
    id: "2",
    email: "aoife.kelly@email.ie",
    name: "Aoife Kelly",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face",
    location: "Cork",
    bio: "Qualified maths teacher and tutor. Happy to trade tutoring for help around the house!",
    credits: 30,
    verificationStatus: "verified",
    badges: [mockBadges[0], mockBadges[1], mockBadges[2]],
    joinedAt: new Date("2024-01-15"),
    completedTrades: 8,
    rating: 5.0,
  },
  {
    id: "3",
    email: "padraig.odonoghue@email.ie",
    name: "Pádraig O'Donoghue",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    location: "Galway",
    bio: "Landscape gardener and green-thumb enthusiast. Looking for tech support and pet sitting.",
    credits: 60,
    verificationStatus: "verified",
    badges: [mockBadges[0], mockBadges[3]],
    joinedAt: new Date("2024-02-01"),
    completedTrades: 15,
    rating: 4.8,
  },
  {
    id: "4",
    email: "siobhan.brennan@email.ie",
    name: "Siobhán Brennan",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    location: "Dublin",
    bio: "Experienced childminder and former creche manager. Would love gardening help!",
    credits: 25,
    verificationStatus: "pending",
    badges: [mockBadges[0]],
    joinedAt: new Date("2024-03-01"),
    completedTrades: 3,
    rating: 4.7,
  },
];

export const mockServices: Service[] = [
  {
    id: "1",
    userId: "1",
    user: mockUsers[0],
    title: "Professional Tiling Services",
    description: "High-quality tiling for bathrooms, kitchens, and floors. 15 years of experience with all tile types including ceramic, porcelain, and natural stone. Free consultations available.",
    category: "home_improvement",
    type: "offer",
    qualifications: ["City & Guilds Tiling Certificate", "15 years experience", "SOLAS registered"],
    estimatedHours: 8,
    creditValue: 40,
    createdAt: new Date("2024-03-01"),
    location: "Dublin",
    status: "active",
  },
  {
    id: "2",
    userId: "1",
    user: mockUsers[0],
    title: "Need Childcare Help",
    description: "Looking for reliable childcare for two children (ages 4 and 7) on weekday afternoons. School pickup and afternoon activities.",
    category: "childcare",
    type: "request",
    estimatedHours: 15,
    creditValue: 45,
    createdAt: new Date("2024-03-05"),
    location: "Dublin",
    status: "active",
  },
  {
    id: "3",
    userId: "2",
    user: mockUsers[1],
    title: "Maths & Science Tutoring",
    description: "Qualified secondary school teacher offering tutoring in Maths and Science for Junior and Leaving Cert students. Patient approach, exam focused.",
    category: "education",
    type: "offer",
    qualifications: ["B.Ed in Mathematics", "5 years teaching experience", "Garda vetted"],
    estimatedHours: 2,
    creditValue: 10,
    createdAt: new Date("2024-03-02"),
    location: "Cork",
    status: "active",
  },
  {
    id: "4",
    userId: "2",
    user: mockUsers[1],
    title: "Need Home Painting Help",
    description: "Looking for someone to help paint our living room and hallway. We'll provide all materials.",
    category: "home_improvement",
    type: "request",
    estimatedHours: 6,
    creditValue: 20,
    createdAt: new Date("2024-03-10"),
    location: "Cork",
    status: "active",
  },
  {
    id: "5",
    userId: "3",
    user: mockUsers[2],
    title: "Garden Design & Maintenance",
    description: "Full garden services from design to ongoing maintenance. Specializing in native Irish plants and sustainable practices. Transform your outdoor space!",
    category: "gardening",
    type: "offer",
    qualifications: ["Horticultural diploma", "10 years experience", "Fully insured"],
    estimatedHours: 4,
    creditValue: 20,
    createdAt: new Date("2024-03-03"),
    location: "Galway",
    status: "active",
  },
  {
    id: "6",
    userId: "3",
    user: mockUsers[2],
    title: "Need Tech Support",
    description: "Looking for help setting up smart home devices and improving WiFi coverage. Have Ring doorbell and Nest thermostat that need configuring.",
    category: "tech_support",
    type: "request",
    estimatedHours: 3,
    creditValue: 15,
    createdAt: new Date("2024-03-08"),
    location: "Galway",
    status: "active",
  },
  {
    id: "7",
    userId: "4",
    user: mockUsers[3],
    title: "Childminding Services",
    description: "Experienced childminder available for regular or occasional care. Former creche manager with 12 years experience. Your home or mine.",
    category: "childcare",
    type: "offer",
    qualifications: ["FETAC Level 6 Childcare", "First Aid certified", "Garda vetted"],
    estimatedHours: 4,
    creditValue: 15,
    createdAt: new Date("2024-03-04"),
    location: "Dublin",
    status: "active",
  },
  {
    id: "8",
    userId: "4",
    user: mockUsers[3],
    title: "Need Garden Makeover",
    description: "Our back garden has been neglected! Looking for help with weeding, lawn care, and possibly planting some flowers.",
    category: "gardening",
    type: "request",
    estimatedHours: 5,
    creditValue: 20,
    createdAt: new Date("2024-03-12"),
    location: "Dublin",
    status: "active",
  },
];

export const mockReviews: Review[] = [
  {
    id: "1",
    fromUserId: "2",
    toUserId: "1",
    fromUser: mockUsers[1],
    tradeId: "t1",
    rating: 5,
    comment: "Seán did an amazing job on our bathroom tiles! Professional, punctual, and the finish is perfect. Would highly recommend.",
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "2",
    fromUserId: "4",
    toUserId: "1",
    fromUser: mockUsers[3],
    tradeId: "t2",
    rating: 5,
    comment: "Excellent work on our kitchen splashback. Very skilled and tidy worker.",
    createdAt: new Date("2024-02-28"),
  },
  {
    id: "3",
    fromUserId: "1",
    toUserId: "2",
    fromUser: mockUsers[0],
    tradeId: "t3",
    rating: 5,
    comment: "Aoife is a fantastic tutor! My son's maths grades have improved significantly.",
    createdAt: new Date("2024-03-01"),
  },
];
