import { ServiceCategory } from "@/types";
import { categoryLabels, categoryIcons } from "./categories";

export interface SkillGuideData {
  slug: string;
  category: ServiceCategory;
  label: string;
  icon: string;
  heroTagline: string;
  intro: string;
  funFacts: string[];
  didYouKnow: string;
  swapIdeas: string[];
  metaDescription: string;
}

export const skillGuides: SkillGuideData[] = [
  {
    slug: "home-improvement",
    category: "home_improvement",
    label: categoryLabels.home_improvement,
    icon: categoryIcons.home_improvement,
    heroTagline: "From dodgy shelves to dream kitchens — Ireland's handiest neighbours are here to help.",
    intro: "Whether it's a leaky tap, a flatpack nightmare, or a full bathroom refit — there's always someone nearby who knows their way around a toolbox. Swap your skills and get the job done without spending a fortune.",
    funFacts: [
      "🏠 Ireland has over 2 million homes, and the average Irish person spends €3,500/year on home improvements.",
      "🔧 DIY is the 3rd most popular hobby in Ireland — right after walking and gardening.",
      "🧱 The oldest inhabited house in Ireland is Kilkenny Castle, built in 1195. Still standing!",
      "🪵 Timber frame construction makes up over 25% of new Irish homes — handy skills are in high demand.",
      "🇮🇪 Fun fact: The phrase 'sure it'll be grand' has been muttered during approximately 98% of Irish DIY projects.",
    ],
    didYouKnow: "The average Irish homeowner tackles 4 DIY projects a year. Imagine swapping your painting skills for someone's plumbing know-how!",
    swapIdeas: ["Tiling for tutoring", "Painting for pet-sitting", "Carpentry for cooking lessons", "Plumbing for photography"],
    metaDescription: "Find home improvement help across Ireland through skill swapping. Trade DIY, tiling, plumbing, and carpentry skills with your neighbours on SwapSkills.",
  },
  {
    slug: "childcare",
    category: "childcare",
    label: categoryLabels.childcare,
    icon: categoryIcons.childcare,
    heroTagline: "It takes a village — and in Ireland, the village is ready to help.",
    intro: "Childcare in Ireland is among the most expensive in Europe. But what if you could swap a few hours of babysitting for someone teaching your kids guitar? That's the SwapSkills way.",
    funFacts: [
      "👶 Ireland has one of the highest birth rates in Europe — we're a nation of mammies and daddies!",
      "💶 Average childcare costs in Ireland are around €184/week — the 2nd highest in the EU.",
      "🏫 There are over 4,600 registered childcare services across Ireland.",
      "👨‍👩‍👧‍👦 Nearly 1 in 3 Irish parents rely on grandparents for some childcare support.",
      "🎪 Irish kids attend an average of 6 birthday parties a year. Six. Think of the cake.",
    ],
    didYouKnow: "Parents who swap babysitting hours save an average of €200/month. That's your family holiday fund right there!",
    swapIdeas: ["Babysitting for gardening help", "After-school minding for home cooking", "Weekend childcare for tech support", "Playdate hosting for music lessons"],
    metaDescription: "Find childcare help through skill swapping in Ireland. Exchange babysitting, after-school care, and family support with trusted neighbours on SwapSkills.",
  },
  {
    slug: "education",
    category: "education",
    label: categoryLabels.education,
    icon: categoryIcons.education,
    heroTagline: "Share what you know. Learn what you don't. It's that simple.",
    intro: "From Leaving Cert grinds to learning a new language — education is one of the most swapped skills on our platform. Everyone's an expert in something.",
    funFacts: [
      "📚 Ireland has one of the highest literacy rates in the world at 99%.",
      "🎓 Over 60% of 25-34 year olds in Ireland have a third-level qualification — the highest in the EU.",
      "🏆 Ireland has produced 4 Nobel Prize winners in Literature alone. We love a good story!",
      "📖 The Book of Kells dates back to 800 AD — Irish education has deep roots.",
      "🇮🇪 Irish (Gaeilge) is taught in every school, but only 1.7% use it as a daily language. Fancy a swap to practice?",
    ],
    didYouKnow: "Private tutoring in Ireland costs €25-50/hour. By swapping, you're saving serious money while helping someone else learn too.",
    swapIdeas: ["Maths tutoring for guitar lessons", "Irish language for tech help", "Exam prep for fitness coaching", "English lessons for cooking classes"],
    metaDescription: "Find tutoring and education swaps in Ireland. Exchange teaching skills, grinds, and language lessons with your community on SwapSkills.",
  },
  {
    slug: "gardening",
    category: "gardening",
    label: categoryLabels.gardening,
    icon: categoryIcons.gardening,
    heroTagline: "Ireland's 40 shades of green didn't happen by accident. 🌿",
    intro: "With our famously wet weather, things grow like mad in Ireland. Whether you need help taming a jungle or want to start your first veggie patch, there's a green-fingered neighbour ready to swap.",
    funFacts: [
      "🌱 Ireland has over 500,000 home gardens — that's a lot of lawns to mow!",
      "☘️ The shamrock isn't just lucky — it's one of over 800 native plant species in Ireland.",
      "🥔 The average Irish household grows 3 types of vegetables at home. Potatoes are, unsurprisingly, #1.",
      "🌧️ Ireland gets 150-225 rain days per year. Your garden basically waters itself!",
      "🐝 Ireland has 98 species of wild bees. Pollinator-friendly gardens are a growing trend (pun intended).",
    ],
    didYouKnow: "Garden maintenance services cost €30-50/hour in Ireland. Swap your tech skills for someone's green thumb and watch your garden bloom!",
    swapIdeas: ["Garden design for photography", "Lawn care for home cooking", "Veggie growing for childcare", "Tree pruning for music lessons"],
    metaDescription: "Find gardening help through skill swapping in Ireland. Exchange garden design, lawn care, and growing tips with neighbours on SwapSkills.",
  },
  {
    slug: "cleaning",
    category: "cleaning",
    label: categoryLabels.cleaning,
    icon: categoryIcons.cleaning,
    heroTagline: "A clean house, a clear mind — and not a cent spent.",
    intro: "Whether it's a deep clean before the in-laws visit or regular help keeping things tidy, cleaning is one of those tasks everyone needs but not everyone enjoys. Lucky there's someone who does!",
    funFacts: [
      "🧹 The average Irish person spends 5 hours per week cleaning — that's 10 full days a year!",
      "🧼 Ireland spends €1.2 billion on cleaning products annually. We're a clean bunch!",
      "✨ Spring cleaning is a tradition dating back centuries in Ireland — tied to preparing the house for Easter.",
      "🏡 Professional cleaning services cost €15-25/hour in Ireland.",
      "🧤 Marie Kondo has nothing on the Irish mammy's cleaning standards. Nothing.",
    ],
    didYouKnow: "Swapping 3 hours of cleaning for 3 hours of tutoring saves both people around €75. Everyone wins!",
    swapIdeas: ["Deep cleaning for tech support", "Regular tidying for cooking meals", "Window cleaning for gardening", "Organising for fitness coaching"],
    metaDescription: "Find cleaning help through skill swapping in Ireland. Exchange house cleaning and organising skills with your community on SwapSkills.",
  },
  {
    slug: "cooking",
    category: "cooking",
    label: categoryLabels.cooking,
    icon: categoryIcons.cooking,
    heroTagline: "From boxty to biryani — Ireland's kitchens are getting creative.",
    intro: "Ireland's food scene has exploded in the last decade. Whether you're a master baker or can barely boil an egg, there's someone ready to swap cooking skills with you.",
    funFacts: [
      "🍳 Ireland consumes 4 million cups of tea per day. We're the 2nd biggest tea drinkers per capita in the world!",
      "🥔 The Irish eat about 85kg of potatoes per person per year. We really do love our spuds.",
      "🍞 Soda bread was invented in Ireland in the 1830s and is still a staple in most homes.",
      "🧈 Kerrygold is sold in over 80 countries. Irish butter is a global superstar.",
      "🍀 Ireland has 2 Michelin-starred restaurants. Our food game is strong.",
    ],
    didYouKnow: "A cooking class in Dublin costs €60-100 per session. Swap your gardening or tech skills for a personal cooking lesson instead!",
    swapIdeas: ["Meal prep for gardening", "Baking lessons for photography", "Catering help for home improvement", "Cultural cooking for language lessons"],
    metaDescription: "Find cooking and catering skills through swapping in Ireland. Exchange recipes, meal prep, and culinary skills with neighbours on SwapSkills.",
  },
  {
    slug: "pet-care",
    category: "pet_care",
    label: categoryLabels.pet_care,
    icon: categoryIcons.pet_care,
    heroTagline: "Because every good boy (and girl) deserves the best. 🐾",
    intro: "Ireland is a nation of pet lovers. But between vet bills, grooming, and dog walking, our furry friends can be expensive. Why not swap some pet care with a neighbour?",
    funFacts: [
      "🐕 Over 500,000 dogs are registered in Ireland. That's a lot of walkies!",
      "🐱 Ireland has approximately 300,000 pet cats — mostly plotting world domination.",
      "🏥 Average annual vet costs per pet in Ireland: €300-500.",
      "🦴 Dog walking services cost €10-20 per walk in Ireland.",
      "🐴 Ireland has more horses per capita than any other European country. Of course we do.",
    ],
    didYouKnow: "Pet sitting while someone's on holiday costs €25-40/day in Ireland. Swap it for cooking, tutoring, or anything else you're good at!",
    swapIdeas: ["Dog walking for gardening", "Pet sitting for home cooking", "Cat minding for tech support", "Dog grooming for photography"],
    metaDescription: "Find pet care help through skill swapping in Ireland. Exchange dog walking, pet sitting, and grooming with trusted neighbours on SwapSkills.",
  },
  {
    slug: "transportation",
    category: "transportation",
    label: categoryLabels.transportation,
    icon: categoryIcons.transportation,
    heroTagline: "Getting from A to B without the bus éireann drama.",
    intro: "Rural Ireland knows the pain of limited public transport. Swap a lift to town for some garden help, or trade airport runs for cooking lessons. It's community transport at its finest.",
    funFacts: [
      "🚗 Ireland has about 2.2 million registered cars — almost one per person over 18.",
      "🚌 Only 10% of people in rural Ireland rely on public transport. Lifts are gold!",
      "🛣️ Ireland has over 99,000 km of roads. That's enough to circle the Earth 2.5 times.",
      "✈️ Dublin Airport handles over 33 million passengers a year. That's a lot of airport runs.",
      "🚲 Cycling has grown by 40% in Irish cities since 2020. Healthy and eco-friendly!",
    ],
    didYouKnow: "A taxi to Dublin Airport from the city centre costs €25-35. Swap a lift with a neighbour and both of you save!",
    swapIdeas: ["Airport lifts for home cooking", "School runs for gardening", "Furniture moving for tech help", "Driving lessons for tutoring"],
    metaDescription: "Find transport help through skill swapping in Ireland. Exchange lifts, deliveries, and moving help with your community on SwapSkills.",
  },
  {
    slug: "tech-support",
    category: "tech_support",
    label: categoryLabels.tech_support,
    icon: categoryIcons.tech_support,
    heroTagline: "\"Have you tried turning it off and on again?\" — just the start of what we offer.",
    intro: "From setting up WiFi to building a website, tech skills are in massive demand across Ireland. And the best part? You can help someone remotely — no house visit needed!",
    funFacts: [
      "💻 Ireland is the European HQ for Google, Apple, Meta, and Microsoft. We're a tech nation!",
      "📱 93% of Irish adults own a smartphone.",
      "👴 Over 40% of people aged 65+ in Ireland struggle with basic digital tasks. They need your help!",
      "🌐 Ireland has the 4th fastest broadband in Europe.",
      "🎮 The gaming industry in Ireland is worth €2 billion. Not just tech support — tech everything!",
    ],
    didYouKnow: "A one-hour tech support call-out costs €50-80 in Ireland. Swap it for baking, gardening, or a lift to the airport instead.",
    swapIdeas: ["Website help for cooking lessons", "Phone setup for gardening", "Computer repair for home improvement", "Social media help for pet care"],
    metaDescription: "Find tech support through skill swapping in Ireland. Exchange computer help, website building, and digital skills with neighbours on SwapSkills.",
  },
  {
    slug: "fitness",
    category: "fitness",
    label: categoryLabels.fitness,
    icon: categoryIcons.fitness,
    heroTagline: "No gym membership? No problem. Your neighbourhood is the gym.",
    intro: "Personal training, yoga, running buddies, or just someone to keep you accountable — fitness swaps are one of the most popular categories on SwapSkills.",
    funFacts: [
      "💪 Over 1.3 million Irish people have gym memberships — that's 26% of adults!",
      "🏃 The Dublin Marathon has 25,000 runners every year. Ireland loves a good run.",
      "🧘 Yoga participation in Ireland has doubled since 2018.",
      "🏊 Ireland has over 70 public swimming pools and countless wild swimming spots.",
      "☀️ Parkrun Ireland has over 100 free weekly events. Community fitness at its finest!",
    ],
    didYouKnow: "A personal trainer in Ireland charges €40-70 per session. Swap your cooking or tech skills for free fitness coaching!",
    swapIdeas: ["Personal training for photography", "Yoga sessions for gardening", "Running coaching for cooking", "Fitness classes for tutoring"],
    metaDescription: "Find fitness and wellness swaps in Ireland. Exchange personal training, yoga, and exercise skills with your community on SwapSkills.",
  },
  {
    slug: "beauty",
    category: "beauty",
    label: categoryLabels.beauty,
    icon: categoryIcons.beauty,
    heroTagline: "Looking your best without spending a fortune. Now that's beautiful.",
    intro: "Nails, makeup, skincare — beauty services in Ireland don't come cheap. But what if your neighbour is a trained beautician who'd love some gardening help in return?",
    funFacts: [
      "💅 The Irish beauty industry is worth over €1 billion annually.",
      "💇 The average Irish woman spends €1,200/year on beauty treatments.",
      "🧴 Ireland's natural skincare brands (like Pestle & Mortar) are world-famous.",
      "💄 Beauty therapy is one of the top 10 most popular apprenticeships in Ireland.",
      "✨ Bridal beauty packages in Ireland cost €300-600. Swapping could save the day!",
    ],
    didYouKnow: "A gel manicure costs €30-45 in Ireland. Swap your tutoring or tech skills for a pamper session instead!",
    swapIdeas: ["Makeup for photography", "Nails for cooking lessons", "Skincare advice for gardening", "Hair styling for tech support"],
    metaDescription: "Find beauty services through skill swapping in Ireland. Exchange makeup, nails, and skincare skills with neighbours on SwapSkills.",
  },
  {
    slug: "barbering",
    category: "barbering",
    label: categoryLabels.barbering,
    icon: categoryIcons.barbering,
    heroTagline: "A fresh cut and a good chat — the Irish barbershop experience.",
    intro: "Barbering is an art form in Ireland, and there are talented people everywhere who'd love to swap a haircut for something they need. Fresh fade for some fresh cooking? Why not!",
    funFacts: [
      "✂️ The average Irish man gets a haircut every 4-6 weeks.",
      "💈 A men's haircut in Ireland costs €15-30 depending on location.",
      "🧔 Beard grooming services have grown by 300% in Ireland since 2015.",
      "🏪 There are over 2,000 barbershops across Ireland — more per capita than most EU countries.",
      "🎭 The traditional Irish barber was also a surgeon in medieval times. We've come a long way!",
    ],
    didYouKnow: "Getting a haircut every month costs €180-360/year. Swap those grooming skills and save — or earn some help around the house!",
    swapIdeas: ["Haircuts for gardening", "Beard trims for cooking", "Hair styling for photography", "Grooming for tech support"],
    metaDescription: "Find barbering and grooming through skill swapping in Ireland. Exchange haircuts and grooming skills with your community on SwapSkills.",
  },
  {
    slug: "arts-crafts",
    category: "crafts",
    label: categoryLabels.crafts,
    icon: categoryIcons.crafts,
    heroTagline: "Ireland's creative spirit is alive and well — and it's ready to swap.",
    intro: "From pottery to painting, knitting to woodwork — Ireland's crafting community is thriving. Share your creative talents and pick up a new hobby through swapping.",
    funFacts: [
      "🎨 Over 30,000 people work in Ireland's creative arts sector.",
      "🧶 Aran sweaters from the Aran Islands are known worldwide — each pattern tells a family story.",
      "🏺 Irish pottery and ceramics are exported to over 50 countries.",
      "🖼️ The National Gallery of Ireland is free to visit and attracts 1 million visitors a year.",
      "✏️ Illustration and graphic design are the fastest-growing creative skills in Ireland.",
    ],
    didYouKnow: "Art classes in Ireland cost €20-50 per session. Swap your practical skills for creative ones and discover a hidden talent!",
    swapIdeas: ["Painting lessons for gardening", "Pottery for cooking", "Knitting for tech support", "Photography for woodwork"],
    metaDescription: "Find arts and crafts swaps in Ireland. Exchange creative skills like painting, pottery, and crafting with neighbours on SwapSkills.",
  },
  {
    slug: "music",
    category: "music",
    label: categoryLabels.music,
    icon: categoryIcons.music,
    heroTagline: "From trad sessions to TikTok covers — Ireland runs on music. 🎶",
    intro: "Ireland has music in its DNA. Whether you're learning the bodhrán or teaching someone piano, music swaps bring pure joy to both sides.",
    funFacts: [
      "🎵 Ireland has more traditional musicians per capita than any other country in the world.",
      "🎸 U2, Hozier, The Cranberries, Sinéad O'Connor — Irish musicians punch well above our weight!",
      "🎻 Comhaltas has over 400 branches worldwide promoting Irish traditional music.",
      "🎤 Over 200,000 Irish people play a musical instrument regularly.",
      "🎼 Music lessons in Ireland cost €25-50 per half hour. That adds up fast!",
    ],
    didYouKnow: "A year of weekly guitar lessons costs €1,300-2,600 in Ireland. Swap your gardening or cooking skills and learn for free!",
    swapIdeas: ["Guitar lessons for tech support", "Singing coaching for cooking", "Piano for gardening", "Bodhrán for photography"],
    metaDescription: "Find music and entertainment swaps in Ireland. Exchange instrument lessons, singing, and music skills with your community on SwapSkills.",
  },
  {
    slug: "photography",
    category: "photography",
    label: categoryLabels.photography,
    icon: categoryIcons.photography,
    heroTagline: "Capture the moment. Swap the skill. Keep the memories.",
    intro: "Everyone needs photos — for social media, events, business, or just for fun. If you've got an eye for a good shot, your skills are in serious demand.",
    funFacts: [
      "📷 Ireland is one of the most photographed countries on Instagram — #Ireland has over 30 million posts.",
      "📸 Professional photography costs €100-300/hour in Ireland.",
      "🌅 The Wild Atlantic Way is 2,600km of pure photographic gold.",
      "🤳 The average Irish person takes 5 photos per day on their phone.",
      "🎥 Video content creation has grown by 200% in Irish businesses since 2020.",
    ],
    didYouKnow: "A family portrait session costs €150-300 in Ireland. Swap your cooking, gardening, or DIY skills for professional photos instead!",
    swapIdeas: ["Portrait sessions for home improvement", "Event photography for cooking", "Product photos for tech support", "Video editing for music lessons"],
    metaDescription: "Find photography and video swaps in Ireland. Exchange camera skills, editing, and creative media with neighbours on SwapSkills.",
  },
  {
    slug: "holistic-wellness",
    category: "holistic_wellness",
    label: categoryLabels.holistic_wellness,
    icon: categoryIcons.holistic_wellness,
    heroTagline: "Mind, body, and soul — Ireland's wellness community has you covered.",
    intro: "From reiki to reflexology, meditation to massage — holistic wellness is booming in Ireland. Swap your practical skills for some much-needed self-care.",
    funFacts: [
      "🧘 Over 500,000 Irish people practice some form of meditation or mindfulness.",
      "💆 The wellness industry in Ireland is worth over €2 billion.",
      "🌿 Irish herbalism has roots going back over 2,000 years to the druids.",
      "🕯️ Aromatherapy is the fastest-growing wellness practice in Ireland.",
      "🏥 70% of Irish adults say stress management is their #1 health concern.",
    ],
    didYouKnow: "A massage session costs €50-90 in Ireland. Swap your tech or gardening skills for some well-deserved relaxation!",
    swapIdeas: ["Massage for photography", "Reiki for cooking", "Meditation classes for gardening", "Reflexology for tech support"],
    metaDescription: "Find holistic wellness swaps in Ireland. Exchange massage, meditation, reiki, and wellness skills with your community on SwapSkills.",
  },
  {
    slug: "coaching-mentoring",
    category: "coaching_mentoring",
    label: categoryLabels.coaching_mentoring,
    icon: categoryIcons.coaching_mentoring,
    heroTagline: "Everyone needs a guide sometimes. Be one. Find one.",
    intro: "Life coaching, career mentoring, business advice — these are skills that change lives. And on SwapSkills, you can access them through the power of community.",
    funFacts: [
      "🧭 The coaching industry in Ireland is worth over €100 million.",
      "🎯 85% of people who receive coaching report increased self-confidence.",
      "💼 Career coaching costs €80-150/hour in Ireland.",
      "📈 Ireland has over 1,500 certified life coaches.",
      "🤝 Mentoring programmes show a 20% increase in career progression for participants.",
    ],
    didYouKnow: "A 6-session coaching programme costs €500-900 in Ireland. Swap your practical skills and get guided by an expert for free!",
    swapIdeas: ["Life coaching for photography", "Career mentoring for gardening", "Business advice for cooking", "CV help for tech support"],
    metaDescription: "Find coaching and mentoring through skill swapping in Ireland. Exchange life coaching, career guidance, and business mentoring on SwapSkills.",
  },
  {
    slug: "local-goods",
    category: "local_goods",
    label: categoryLabels.local_goods,
    icon: categoryIcons.local_goods,
    heroTagline: "Fresh eggs, homemade jam, and everything in between. 🥚",
    intro: "Ireland's local producers are incredible — from free-range eggs to artisan cheese, homemade preserves to fresh honey. Swap your skills for genuine local produce.",
    funFacts: [
      "🥚 Ireland produces over 600 million eggs per year. That's a lot of breakfast rolls!",
      "🍯 Irish honey is among the most prized in Europe due to our wildflower diversity.",
      "🧀 Ireland exports cheese to over 50 countries. We know our cheddar!",
      "🌾 Farmers' markets in Ireland have grown by 150% in the last decade.",
      "🥛 Ireland produces enough milk to fill 1.5 billion litres annually. Moo-re than enough!",
    ],
    didYouKnow: "Organic, locally-produced food costs 20-40% more than supermarket equivalents. Swap your skills directly with producers for the freshest goods!",
    swapIdeas: ["Eggs for tech support", "Homemade bread for photography", "Preserves for gardening help", "Honey for tutoring"],
    metaDescription: "Find local goods and produce through swapping in Ireland. Exchange fresh eggs, homemade food, and artisan products with your community on SwapSkills.",
  },
];

export function getSkillGuideBySlug(slug: string): SkillGuideData | undefined {
  return skillGuides.find(g => g.slug === slug);
}

export function getCategorySlug(category: ServiceCategory): string | undefined {
  return skillGuides.find(g => g.category === category)?.slug;
}
